### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by g-ongetta** [ZakisM/neofetch_mac#1]
Output:
```
thread 'main' panicked at 'invalid time', /Users/zak/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/naive/time.rs:412:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

MacOS Version: 10.15.6

**Comment by g-ongetta** [comment]
Full backtrace:
```
thread 'main' panicked at 'invalid time', /Users/zak/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/naive/time.rs:412:67
stack backtrace:
   0:        0x1066ae0f4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4b962ed89f71a03
   1:        0x1066c96f0 - core::fmt::write::h94ae1e793baa7a00
   2:        0x1066ac00b - std::io::Write::write_fmt::h5c716758fdc3057f
   3:        0x1066afa35 - std::panicking::default_hook::{{closure}}::hc6119c7d16548caf
   4:        0x1066af777 - std::panicking::default_hook::heae8b62897b351dc
   5:        0x1066affd5 - std::panicking::rust_panic_with_hook::hc36596b4257bea99
   6:        0x1066afb6b - std::panicking::begin_panic_handler::{{closure}}::h49e5ddc3f21ca2fb
   7:        0x1066ae568 - std::sys_common::backtrace::__rust_end_short_backtrace::h9bd32c9ad3fad18f
   8:        0x1066afb2a - _rust_begin_unwind
   9:        0x1066d125f - core::panicking::panic_fmt::hcdc9362d34d55302
  10:        0x1066d10ea - core::option::expect_failed::h2cf6417a1cce758c
  11:        0x10660103a - neofetch_mac::systemctl::get_systemctl_info::hd527facb21f59eb3
  12:        0x1066079ab - neofetch_mac::main::h9f9b42e1ba278ec7
  13:        0x10660316a - std::sys_common::backtrace::__rust_begin_short_backtrace::h8cc7d72519a77deb
  14:        0x10660318c - std::rt::lang_start::{{closure}}::h9d3165d92690b1d3
  15:        0x1066b02b0 - std::rt::lang_start_internal::hd0c760d47f593c0a
  16:        0x1066080f9 - _main
--------------------------------
```

**Comment by ZakisM** [comment]
Should be fixed in #2
